# Site setings
name: 'devislife'
description: 'Web Developer'
meta_description: '백엔드 개발자의 IT일기'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author: 
  image: 'profileImg.jpg'
  greetings: "Hyunsik Lee. Back-End Developer. Dev is life."
favicon: 'assets/images/profileImg.jpg'
baseurl: 
production_url: https://hs95blue.github.io/
disqus: 'hs95blue'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: hs95blue@gmail.com
contact_page_description: "Contact me"
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'username'
facebook: 'username'
github: 'hs95blue'
codepen: 'username'
dribbble: 'username'
medium: '@username'
instagram: 'hyeonsik Lee'
pinterest: 'username'
linkedin: 'username'
producthunt: '@username'
quora: 'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Style Guide
    url: /style-guide
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
